// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTsA0UDftTpiBMz3X3EOuKguOGUHmuJg',
    appId: '1:237348515668:web:9a9b0c17ac2cd09cf262c1',
    messagingSenderId: '237348515668',
    projectId: 'chat-app-5c5b5',
    authDomain: 'chat-app-5c5b5.firebaseapp.com',
    storageBucket: 'chat-app-5c5b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHj_14xTpKrs2w9uV5qPd4_Xd24jQBqPU',
    appId: '1:237348515668:android:2f0f92c3f1320888f262c1',
    messagingSenderId: '237348515668',
    projectId: 'chat-app-5c5b5',
    storageBucket: 'chat-app-5c5b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeYZjVU8BwQ5cV6KalbX8FFbxcWnyAj84',
    appId: '1:237348515668:ios:6d9606a2b16e5e1df262c1',
    messagingSenderId: '237348515668',
    projectId: 'chat-app-5c5b5',
    storageBucket: 'chat-app-5c5b5.appspot.com',
    androidClientId: '237348515668-apklhe8oerpmc8mcmf0slc6nq2dj8ko4.apps.googleusercontent.com',
    iosClientId: '237348515668-11h12aqshavmfith1mtauma5ic75v0de.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
